server {
    listen 8080;
    server_name _;

    location = / {
        return 302 /ais/;
    }

    location = /ais {
        return 301 /ais/;
    }

    location /ais/ {
        alias /srv/ais/web/;
        index index.html;
    }

    location = /upload {
        return 301 /upload/;
    }

    location /upload/ {
        proxy_pass http://127.0.0.1:9080/upload/;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        client_max_body_size 600M;
    }

    location ~* ^/ais/files/([^/]+\.(jpg|jpeg|png))$ {
        alias /srv/ais/images/$1;
    }

    location / {
        return 404;
    }
}
